export enum BusinessType {
    PHARMACY = 'PHARMACY',
    GROCERY = 'GROCERY',
    SUPER_SHOP = 'SUPER_SHOP',
    CLOTHING = 'CLOTHING',
    ELECTRONICS = 'ELECTRONICS',
    COSMETICS = 'COSMETICS',
    BAKERY = 'BAKERY',
    RESTAURANT = 'RESTAURANT',
    STATIONERY = 'STATIONERY',
    CUSTOM = 'CUSTOM'
}