export enum ExpenseCategory {
    RENT = 'RENT',
    SALARY = 'SALARY',
    ELECTRICITY = 'ELECTRICITY',
    INTERNET = 'INTERNET',
    TRANSPORT = 'TRANSPORT',
    MARKETING = 'MARKETING',
    MAINTENANCE = 'MAINTENANCE',
    MISCELLANEOUS = 'MISCELLANEOUS'
}